name: HealthAIoT
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - asttokens=2.0.5
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.1.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=0.8.3
  - flask=3.0.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - h2=4.1.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.7
  - imbalanced-learn=0.12.4
  - importlib-metadata=8.6.1
  - ipython=8.30.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libllvm14=14.0.6
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.45.3
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - ncurses=6.4.20240210
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.8.0
  - pillow=10.4.0
  - pip=24.2
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycparser=2.22
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - shap=0.46.0
  - six=1.16.0
  - slicer=0.0.8
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.4
  - tbb=2021.10.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - tree=2.1.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - werkzeug=3.0.3
  - wheel=0.44.0
  - xz=5.4.6
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - alembic==1.14.1
      - colorlog==6.9.0
      - filelock==3.16.1
      - fsspec==2024.10.0
      - mako==1.3.8
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - optuna==4.2.0
      - pyyaml==6.0.2
      - sqlalchemy==2.0.37
      - sympy==1.13.1
      - torch==2.7.0.dev20250130
      - torchaudio==2.6.0.dev20250130
      - torchvision==0.22.0.dev20250130
      - tqdm==4.67.1
      - ucimlrepo==0.0.7
